### ISSUE TITLE
Add to Data Science folder

### ISSUE THREAD

**Issue by tomriddle77** [tomriddle77/Hacktober22#81]

**Comment by Amulya77** [comment]
please assign me this issue

**Comment by bharath-acchu** [comment]
@tomriddle77  Could please assign me this

**Comment by pranay202** [comment]
@tomriddle77 Could you please assign me this?

**Comment by pranay202** [comment]
@tomriddle77 please review my PR!

**Comment by shahrushi2003** [comment]
Please assign this issue to me.

**Comment by Ashish93-mrx** [comment]
hello sir!! i would like to add, please assign me this issue.
